### ISSUE TITLE
[Bug] Birds Flying Launch Bug

### ISSUE THREAD

**Issue by MLGMagicHoodini** [0SoggyMustache0/ZAWA#3] opened 2020-03-22 19:53 UTC
**Describe the bug**
Birds sometimes will get stuck on blocks (corners) and then launched at highspeeds in a direction and disappear seems like

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1.Had a box (with roof and walls and floor)
2.Spawned some toucans
3.Then used WorldEdit to remove a wall and roof to let then free

**Expected behavior**
They should just fly normally instead of being launched 100kmh+ towards a direction

**Screenshots**

** Crash Report or Game Log**
If your game crashed, paste your crash report to https://pastebin.com/ or similar service and paste the link in place of this sentence.

**Please complete the following information):**
 - Mod Version Number : 2.0.0
 - Bookworm Version Number : 2.5.0
 - Forge Version Number : 2846
 - Is OptiFine installed? : Yes

**Additional context**
Add any other context about the problem in place of this sentence.

**Comment by 0SoggyMustache0** [comment] 2020-03-22 19:58
Duplicate of #4 . Leaving 4 as it is more descriptive.

**Closed by 0SoggyMustache0** 2020-03-22 19:58 UTC
Labels: duplicate
