### ISSUE TITLE
[Bug] Poacher spawn rate out of control

### ISSUE THREAD

**Issue by DBSeamz** [0SoggyMustache0/ZAWA#192] opened 2021-01-18 20:11 UTC
**Describe the bug**
So many poachers are spawning that they're preventing the spawning of other animals.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Testing ZAWA in a Creative mode world (1.12.2). Found a Village in between a Savanna and a Desert.
2. Switched Difficulty to Peaceful while I built a fence around the village so no one would be eaten by zombies.
3. Dozens of Poachers spawned in and around the village while I was doing this.
4. Since the world was in Peaceful difficulty, the poachers didn't shoot anything, but there were so many it appeared nothing else was spawning.

**Expected behavior**
I expected Poachers to be a semi-rare threat: you'd encounter one every so often and if you got unlucky you might meet more than one in the same place. They should be somewhat of a hindrance to building a zoo, but they shouldn't completely stop the player from being able to do so.

**Screenshots**
![2021-01-18_14 53 16](https://user-images.githubusercontent.com/68706057/104958808-b74e5100-599e-11eb-93c5-9e2b6660c76a.png)
![2021-01-18_14 55 34](https://user-images.githubusercontent.com/68706057/104958818-bb7a6e80-599e-11eb-8f11-e61c77026538.png)

**Please complete the following information):**
 - Mod Version Number : zawa-1.12.2-2.1.0
 - Bookworm Version Number : bookworm-1.12.2-2.5.2.1
 - Forge Version Number : forge-14.23.5.2847
 - Are other mods installed? : Yes, it's a modpack (Isla Unga Bunga)
 - Is OptiFine installed? :  Yes
 - Is this bug present in single player or on a server or both? : Singleplayer

**Comment by JoelZBub** [comment] 2021-01-23 17:37
Duplicate of
#172 #169 #166 #134 #133 #132 #92 #90 #81 #77 #76 #52 #50 #46 #29 #28

**Comment by JoelZBub** [comment] 2021-01-23 17:38
This crap right here is why I left this mod.

**Closed** 2021-01-23 17:42 UTC
