### ISSUE TITLE
Poachers won't stop spawning even after disabling the config

### ISSUE THREAD

**Issue by pwuppi** [0SoggyMustache0/ZAWA#81] opened 2020-05-05 13:08 UTC
**Describe the bug**
Poachers won't stop spawning in pairs even when disabled in the configs.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. I made a new world to build a zoo.
2. Disabled mob spawning via gamerule at first.
3. Noticed poachers wouldn't stop spawning even after.
4. Disabled animal spawns in the mod options just to see if that would work, it didn't.
5. Went to the config files and set all their spawns to 0, put it to false and took out the biome which I was building in (plains). It still didn't stop them from spawning

**Expected behavior**
For them to stop spawning just after the gamerule

**Screenshots**

** Crash Report or Game Log**
If your game crashed, paste your crash report to https://pastebin.com/ or similar service and paste the link in place of this sentence.

**Please complete the following information):**
 - Mod Version Number : 1.12.2-2.0.35
 - Bookworm Version Number : 1.12.2-2.5.1
 - Forge Version Number : 1.12.2-14.23.5.2838
 - Are other mods installed? : Yes
 - Is OptiFine installed? : Yes
 - Is this bug present in single player or on a server or both? : Single player
 
**Additional context**
I may begin saying I do have 93 mods (counting zawa and bookworm) but this has never happened before until now. Also I know my forge is a little outdated but even when I updated forge it would happen, so I decided to downgrade to when I remember it wouldn't do it and it still would happen.

**Comment by JoelZBub** [comment] 2020-05-05 13:36
Duplicate of #77 #52 #50 #46 #29 

Please read closed issues before making a report.
Also remove Custom Mob Spawner.

**Closed by JoelZBub** 2020-05-05 13:36 UTC
