### ISSUE TITLE
[CONFLICT] Mobs do not spawn on server

### ISSUE THREAD

**Issue by Thomas12323** [0SoggyMustache0/ZAWA#42] opened 2020-04-05 11:35 UTC
Integrated into existing server to get some more animals, flew around a lot but did not find any mob spawns other than the vanilla ones.

Using the Sponge Server with latest 12.2.2 Forge
Current modlist:

`
ActuallyAdditions-1.12.2-r151-2

AmbientSounds_v3.0.4_mc1.12.2 
appliedenergistics2-1v6-stable-7 
Aquaculture-1.12.2-1.6.8 
BiomesOPlenty- 11227012444 
universal bookworm- 1122250 
BrandonsCore- 11222418210 
universal CodeChicken Lib- 1122323358 
universal COFHCore- 112246327 
universal CoFHWorld- 11221317 
Draconic-Evolution-1.12.2-2.3.25.351-uni...
extrautils 2112199 
fluxnetworks- 1122401431 
Forgelin-1.8.4 
Gunpowderlib-1.12.2-1.0 
Hwyla-1.8.26-B41 1.12.2 
industrialforegoing- 112211213237 
Integration Foregoing- 1122110 
Inventory Tweaks-1.63 
jei 11224150293 
journeymap- 1122571 
JustEnoughResources- 112209260 
library- 17191122
Mantle- 11213355 
mcjtylib-1.12-3.5.4 
Mekanism- 1122983390
mowziesmobs-1.5.4
OptiFine_1.12.2_HD_U_F5 (only client)
OreExcavation-1.4.150 
Pam's+HarvestCraft+1.12.2zg 
RedstoneFlux- 1122106 universal
refined storage-1.6.15 ftools-1.12-7.73
Roguelike Dungeons- 1122180 
Serene Seasons- 11221218 
universal Spartan Shields- 1122154 
Spartan Weaponry-1.12.2-beta-1.3.8 
TConstruct- 11222130183 
tesla-core-lib- 11221017 
ThermalDynamics- 112225521 universal 02.
Thermal Expansion-1.12.2-5.5.4.43-univer.. 02-
ThermalFoundation- 112226327 unive...
twilightforest- 11223101013
 universal VanillaFix- 1010150(only client) 

Bookworm and of course
zawa- 1122201`

**Comment by JoelZBub** [comment] 2020-04-05 13:32
Duplicate of https://github.com/0SoggyMustache0/ZAWA/issues/22

Thanks for the modlist. This is a place to start.

Please update ZAWA to 2.0.2 and Bookworm to 2.5.1 and go into ungenerated terrain and let us know if you find ZAWA mobs. I tested this yesterday and it worked.

**Comment by 0SoggyMustache0** [comment] 2020-04-06 01:56
Not enough info.

**Closed by 0SoggyMustache0** 2020-04-06 01:56 UTC
Labels: bug, duplicate, more info needed
