### ISSUE TITLE
[Bug] Binocular bug

### ISSUE THREAD

**Issue by iiGenesis** [0SoggyMustache0/ZAWA#127] opened 2020-07-02 13:26 UTC
So I placed a binocular.
Then I tried to place another binocular beside of it

and it glitched somehow :/
You can try it yourself and see what does happens

Thanks!

**Comment by JoelZBub** [comment] 2020-07-02 13:34
Duplicate of #109 
Please follow the template. 
This report gives no actual info.

**Closed by JoelZBub** 2020-07-02 13:34 UTC
Labels: Dont' Do This!, bug, does not follow template, duplicate
