### ISSUE TITLE
[Bug] Water creatures not spawning. Mod conflict. 1.12.2

### ISSUE THREAD

**Issue by HacklesCackles** [0SoggyMustache0/ZAWA#139] opened 2020-07-07 00:27 UTC
Using the Quark mod above a later version than Quark-r1.6-177 will cause ZAWA water mobs not to spawn in the game.

Steps to reproduce the behavior. (What were you doing when this happened) :
1. Running newer quark versions (tried Quark-r1.6-178 & Quark-r1.6-178 - No water creatures. ((Quark-r1.6-177 all spawning works fine!) ) while also running ZAWA version zawa-1.12.2-2.1.0

**Expected behavior**
Water creatures for ZAWA fail to spawn past initial world spawn point.

**Please complete the following information):**
 - Mod Version Number : zawa-1.12.2-2.1.0
 - Bookworm Version Number : bookworm-1.12.2-2.5.2.1
 - Forge Version Number :1.12.2 - 14.23.5.2854
 - Are other mods installed? : 
   |   | ADL-1.1.1.jar 
  |   | AbyssalCraft-1.12.2-1.10.1  
  |   | AnvilFix-1.12.2-1.0.5.jar 
  |   | AutoRegLib-1.3-32.jar 
  |   | Baubles-1.12-1.5.2.jar 
  |   | BiomesOPlenty-1.12.2-7.0.1.2444-universal.jar 
  |   | Bountiful-2.2.2.jar 
  |   | CD4017BE_lib-1.12.2-6.5.0.2.jar 
  |   | Cavern_1.12.2-v2.3.1.jar 
  |   | Ceramics-1.12-1.3.7.jar 
  |   | Chameleon-1.12-4.1.3.jar 
  |   | ChestTransporter-1.12.2-2.8.8.jar 
  |   | ChineseWorkshop-1.12.2_1.2.6.jar 
  |   | Chisel-MC1.12.2-1.0.2.45.jar 
  |   | Chunk+Pregenerator+V1.12-2.3.jar 
  |   | Colored+Redstone-1.3.2.jar 
  |   | ColoredWater-1.12.2-b37.jar 
  |   | CraftTweaker2-1.12-4.1.20.577.jar 
  |   | DeathCounter-1.12.2-1.1.0.jar 
  |   | Dynmap-3.0-beta-4-forge-1.12.2.jar 
  |   | DynmapBlockScan-3.0-beta-1-forge-1.12.2.jar   
  |   | Erebus-1.0.31.jar  
  |   | FastLeafDecay-v14.jar 
  |   | Forgelin-1.8.4.jar  
  |   | Inspirations-1.12.2-0.2.9.jar 
  |   | KleeSlabs_1.12.2-5.4.12.jar 
  |   | Labyrinth-1.12.2-1.0.jar 
  |   | MagmaMonsters-0.3.0.jar 
  |   | Mantle-1.12-1.3.3.55.jar  
  |   | NaturesCompass-1.12.2-1.8.5.jar 
  |   | NomadicTents-1.12.2-9.5.2.jar 
  |   | NotEnoughPets-1.12.2-v2.1.0.jar 
  |   | OceanFloor-1.12.2-1.0.2.jar 
  |   | OreSpawn-1.12-3.3.1.179.jar 
  |   | Pam's+HarvestCraft+1.12.2zg.jar 
  |   | Patchouli-1.0-21.jar 
  |   | PrettyBeaches_1.12.2-1.0.4.jar 
  |   | PyramidPlunder-1.12.2-1.4.jar 
  |   | Quark-r1.6-177.jar 
  |   | RainbowOaks-1.12-1.0.4.jar 
  |   | Roads-1.12.2-1.0.2.jar
  |   | Rocket+Squids+1.12.2-1.0.3.jar 
  |   | SaltyMod-1.12.2-1.12.6.2.jar 
  |   | Schematics-1.12.2.12.jar 
  |   | Signals-1.12.2-1.4.1-30-universal.jar 
  |   | StorageDrawers-1.12.2-5.4.2.jar 
  |   | StorageDrawersUnlimited-1.12.2-1.3.0.jar  
  |   | TorchLever1.12.2-1.0.jar 
  |   | VerticallyStackedDimensions-1.12.2-0.1.9.jar 
  |   | VillageNames-1.12.2-3.3.1.jar 
  |   | Waystones_1.12.2-4.1.0.jar 
  |   | aether_legacy-1.12.2-v1.4.4.jar 
  |   | backpacks+1.12.2+-+3.5.8.jar 
  |   | bewitchment-1.12.2-0.0.22.15.jar 
  |   | bookworm-1.12.2-2.5.2.1.jar 
  |   | brownmooshrooms-1.0.0.jar 
  |   | comfycozy-1.2.jar 
  |   | corpsecomplex-1.12.2-1.0.11.1.jar 
  |   | disenchanter-[1.12]1.6.jar 
  |   | editmobdrops-1.12.2-1.3.0.jar 
  |   | fossilsarcheology-8.0.4.jar 
  |   | hunterillager-1.12.2-1.2.jar
  |   | iceandfire-1.9.1-1.12.2.jar
  |   | incontrol-1.12-3.9.16.jar 
  |   | jei_1.12.2-4.15.0.296.jar 
  |   | journeymap-1.12.2-5.7.1.jar 
  |   | lilcritters-1.12.2-1.1.0.0.jar 
  |   | llibrary-1.7.19-1.12.2.jar 
  |   | lostcities-1.12-2.0.22.jar 
  |   | manawell-1.12--0.0.2.jar
  |   | natura-1.12.2-4.3.2.69.jar 
  |   | qualityoflife-u9.jar 
  |   | reptilemod-1.12.2-3.8.4-89.jar 
  |   | restrictedportals-1.12-0.6.3.jar 
  |   | seedprotect-1.12.2-1.2.0.jar
  |   | shipwrecks-mc1.12.2-2.0.0.jar 
  |   | stone_ladder-0.0.4.jar 
  |   | subterraneanwaters-1.12.2-1.7.9.jar
  |   | tellme-1.12.2-0.7.0-dev.20190610.165828.jar 
  |   | tropicraft-MC1.12.2-7.1.9.115.jar 
  |   | twilightforest-1.12.2-3.10.1013-universal.jar 
  |   | ultimate_unicorn_mod-1.12.2-1.5.16.jar 
  |   | water-erosion-1.12.2-forge-1.1.1-beta1-full.jar  
  |   | weirdinggadget-1.12.2-2.1.16-universal.jar 
  |   | wings-1.1.6-1.12.2.jar 
  |   | worldedit-forge-mc1.12.2-6.1.10-dist.jar 
  |   | worldedit-wanditems-v1.0-mc1.12.2.jar 
  |   | worldutils-1.12.2-0.4.2.jar
  |   | worleycaves-1.5.1.jar
  |   | zawa-1.12.2-2.1.0.jar 

 - Is OptiFine installed? : NO 
 - Is this bug present in single player or on a server or both? :
Server. (Unsure of single player.)

I would have reported the info on the #47 thread but it was closed for me.

**Comment by JoelZBub** [comment] 2020-07-07 00:30
Duplicate of #47

**Closed by JoelZBub** 2020-07-07 00:30 UTC
Labels: duplicate

**Comment by HacklesCackles** [comment] 2020-07-07 00:47
I'm fine with this being closed, I do however hope you are looking into the conflict since I went through all the trouble to find the conflicting mod and other people reporting this problem are running to same Quart mod.

**Comment by HacklesCackles** [comment] 2020-07-07 00:47
*quark

**Comment by JoelZBub** [comment] 2020-07-07 00:54
It's not Quark
