### ISSUE TITLE
[Bug] Sea Mobs not Spawning.

### ISSUE THREAD

**Issue by SheroxGG** [0SoggyMustache0/ZAWA#85] opened 2020-05-11 22:59 UTC
**Issues that dont follow this template will be ignored and closed**

**Describe the bug**
I have a problem on my modpack in which sea mobs are not spawning, I am sure its not your problem, it must be a mod making conflict, but I cant find it, thats why I am posting this here. Maybe you got feedback from this problem happening. Other animals spawn naturally but sea ones doesnt, squids are not spawning neither, but guardians are. 

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Explorating My world
2. I have ZAWA las version
3. I am on a server with sponge forge
4.
More steps...

**Expected behavior**
 Mobs to spawn on the sea

**Screenshots**

** Crash Report or Game Log**
If your game crashed, paste your crash report to https://pastebin.com/ or similar service and paste the link in place of this sentence.

**Please complete the following information):**
 - Mod Version Number : zawa-1.12.2-2.0.35.jar
 - Bookworm Version Number : bookworm-1.12.2-2.5.1.jar
 - Forge Version Number :  forge-14.23.5.2854
 - Are other mods installed? : Yes
Here is a list: 
Just Enough Resources (JER) (by way2muchnoise)
Serene Seasons (by TheAdubbz)
Hwyla (by TehNut)
Potion Core (by Tmtravlr)
Cosmetic Armor Reworked (by LainMI)
Actually Additions (by Ellpeck)
derfl007's Road Mod (by derFl007)
CXLibrary (by cubex2)
PlayerRevive (by CreativeMD)
Ding (by ohaiiChun)
Comforts (by TheIllusiveC4)
iChunUtil (by ohaiiChun)
Mob Dismemberment (by ohaiiChun)
Custom NPCs (by Noppes_)
Hats (by ohaiiChun)
Security Craft (by Geforce132)
Pam's HarvestCraft (by pamharvestcraft)
Quality Tools (by Tmtravlr)
McDonald's Mod (by littlebat10_a)
OpenBlocks Elevator (by vsngarcia)
PTRLib (by RazzleberryFox)
Building Gadgets (by Direwolf20)
Waila Harvestability (by squeek502)
Chisel (by tterrag1098)
Camera Mod (by henkelmax)
CraftStudio API (by ZeAmateis)
Wawla - What Are We Looking At (by DarkhaxDev)
ConnectedTexturesMod (by tterrag1098)
CraftTweaker (by Jaredlll08)
Quark (by Vazkii)
AutoRegLib (by Vazkii)
Torchmaster (by xalcon)
Gliby's Voice Chat Reloaded (by Ivasik78)
MrCrayfish's Furniture Mod (by MrCrayfish)
Obfuscate (by MrCrayfish)
Corail Tombstone (by Corail_31)
Biomes O' Plenty (by Forstride)
Forgiving Void (by BlayTheNinth)
Falling Tree (by RakSrinaNa)
Cooking for Blockheads (by BlayTheNinth)
More Furnaces (by cubex2)
OreLib (by OreCruncher)
Iron Backpacks (by gr8pefish)
Good Ol' Currency (by BeardlessBrady)
MrCrayfish's Vehicle Mod (by MrCrayfish)
Fast Leaf Decay (by olafskiii)
Double Slabs (by CJMinecraft01)
Just Enough Items (JEI) (by mezz)
Iron Chests (by ProgWML6)
BetterFps (by Guichaguri)
Mowzie's Mobs (by bobmowzie)
Aquaculture 2 (by Shadowclaimer)
Faster Ladder Climbing (by maddachshund)
LLibrary (by _ForgeUser11902522)
Roguelike Dungeons (by greymerktv)
Guide-API (by TehNut)
Vending block (by kamildanak)
Spartan Shields (by ObliviousSpartan)
Rustic (by mangoose3039)
CreativeCore (by CreativeMD)
OnlinePictureFrame (by CreativeMD)
Dynamic Surroundings (by OreCruncher)
Chisels & Bits (by AlgorithmX2)
Foamflower (by kamildanak)
Decocraft (by RazzleberryFox)
Animania (by Purplicious_Cow_)
JourneyMap (by techbrew)
Extra Utilities (by RWTema)
MalisisDoors (by Ordinastie)
Exotic Birds (by ThePavoReality)
MalisisCore (by Ordinastie)

 - Is OptiFine installed? : No, Playing on a server
 - Is this bug present in single player or on a server or both? : Both
 
**Additional context**
Thanks a lot for your job and effort making this mod cool! Hope you can help. Have a good day 😄

**Comment by JoelZBub** [comment] 2020-05-11 23:19
Thank you for the nice words. 
This is a duplicate of #47 
Please follow that issue for updates.

**Closed** 2020-07-12 12:20 UTC
Labels: bug, can not replicate issue, duplicate
