### ISSUE TITLE
[Bug] Tamed animals are unable to move.

### ISSUE THREAD

**Issue by Gojiratheking106** [0SoggyMustache0/ZAWA#65] opened 2020-04-22 12:57 UTC
Wild animals are capable of moving just fine, and so do tamed animals at first. However, after a few seconds they'll just stop moving, and if I hit them the animal will start moving its legs extremely fast without moving an inch.

Steps to reproduce the behavior. (What were you doing when this happened) :
1. I spawned the animal
2. The animal was tamed
3. I see the animal stays in place without moving
4. I hit the animal to see if it reacts, the running animation plays but the animal itself doesn't move

I recorded the bug on a new world: https://www.youtube.com/watch?v=O7kThF37Abk&feature=youtu.be

 - Mod Version Number : 2.0.3
 - Bookworm Version Number : 2.5.1
 - Forge Version Number : 14.23.5.287
 - Are other mods installed? : Animania, Coral Reef, Deextinction mod, Doggy Talents, Erebus, Exotic Birds, Fossils and Archeology, Ice and Fire, Inventory Tweaks, Just Enough Items, Steve's Bizarre Adventure, Journey Map, Rats and Story of Life.
 - Is OptiFine installed? : Yes
 - Is this bug present in single player or on a server or both? : I only play single player
 
The bug still happens even with no other mods installed.

**Comment by JoelZBub** [comment] 2020-04-22 18:12
Duplicate of #62 and #63 
[![Screenshot from Gyazo](https://gyazo.com/37b0f6d6f51f34e5a26947476b7249b6/raw)](https://gyazo.com/37b0f6d6f51f34e5a26947476b7249b6)

**Closed** 2020-04-22 18:13 UTC
Labels: bug, duplicate
