### ISSUE TITLE
[Bug] Problem between ZAWA and Performant [ Over 100 AI tasks]

### ISSUE THREAD

**Issue by iFocsy** [0SoggyMustache0/ZAWA#94] opened 2020-06-09 16:25 UTC
**Describe the bug**
While using the mod "Performant" which improve the server AI directly, i get the spam.

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1. Have ZAWA and Performant ON
2. Have a new World or a Existing one
3. Play around with zawa entities
4. Console gets Spammed for some time.

**Expected behavior**
ZAWABaseFlying.onUpdate() working with performant, i have already contacted them and they say this problem is usually on other mods, and it's only ZAWA causing it.

**Screenshots**
![image](https://user-images.githubusercontent.com/16827613/84173914-4a5ff980-aa54-11ea-9c77-854d64b58870.png)

**Crash Report or Game Log**
No crash, just WARN.

**Please complete the following information):**
 - Mod Version Number : zawa-1.12.2-2.0.35
 - Bookworm Version Number : bookworm-1.12.2-2.5.1
 - Forge Version Number : Forge [R] Version 1.12.2 Build 2854
 - Are other mods installed? : Yes when it happened, then i tried only with ZAWA and Performant.
 - Is OptiFine installed? : Yes at start, on the other world as debug test, no.
 - Is this bug present in single player or on a server or both? : Both.

**Comment by 0SoggyMustache0** [comment] 2020-06-09 16:58
Duplicate of #88

**Closed by 0SoggyMustache0** 2020-06-09 16:58 UTC

**Comment by JoelZBub** [comment] 2020-06-09 22:42
Remove performant
