### ISSUE TITLE
A lot of Poachers spawning

### ISSUE THREAD

**Issue by audaciity** [0SoggyMustache0/ZAWA#172] opened 2020-09-18 16:06 UTC
Poachers are spawning a lot around the world. They fill up the map and in the map their head icons are sheep's. I'm just trying to know if this is supposed to be like this or if there is a bug

**Comment by JoelZBub** [comment] 2020-09-18 16:21
Duplicate of
#169 #166 #134 #133 #132 #92 #90 #81 #77 #76 #52 #50 #46 #29 #28

**Closed by JoelZBub** 2020-09-18 16:21 UTC
Labels: Dont' Do This!, does not follow template, invalid
