### ISSUE TITLE
poacher spawning in large numbers

### ISSUE THREAD

**Issue by ajith2005** [0SoggyMustache0/ZAWA#29] opened 2020-04-02 15:58 UTC
**Issues that dont follow this template will be ignored and closed**

**Test before making a report by removing all mods except ZAWA, Bookworm and ZAWA Add-ons. Check that you are using the latest versions of these mods. Delete these lines when making a report.**

**Describe the bug**
when i create a new world it starts spawning huge numbers of poachers

**To Reproduce**
Steps to reproduce the behavior. (What were you doing when this happened) :
1.
2.
3.
4.
More steps...

**Expected behavior**

**Screenshots**

** Crash Report or Game Log**
If your game crashed, paste your crash report to https://pastebin.com/ or similar service and paste the link in place of this sentence.

**Please complete the following information):**
 - Mod Version Number :zawa 2.0.1
 - Bookworm Version Number :2.5.0
 - Forge Version Number :1.12.2 forge version 2847
 - Is OptiFine installed? : yes!
 - Is this bug present in single player or on a server or both? :single player
 
**Additional context**
i switched off MOB SPAWNING still it spawns poacher alone

**Comment by JoelZBub** [comment] 2020-04-02 16:00
Uninstall Custom Mob spawner.

**Comment by JoelZBub** [comment] 2020-04-02 16:04
This is a duplicate of https://github.com/0SoggyMustache0/ZAWA/issues/28 but with even less usable info. If we can't duplicate the issue it can't be fixed.

**Closed by JoelZBub** 2020-04-02 16:04 UTC
